[features]
seeds = false
[programs.localnet]
vault_zeta = "GSNE8nVJ4WYCryAbugFZW7Jiw1VdeDvV1MG2VNqK4S3V"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/georgegeorge/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
